# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f7e29eda29d9833362c71f5c1cb26a6db32dd6ad2cbfb3cad34062725fc00364545f52f112eb4d1313f86129dab3692fcf7cae2ae6875b9d4dd1e1392d2bd1a

test:
  secret_key_base: d80417b9b80416456642d460cd5c40637e3e4877e2f97ccf5de4f241404859a3a29610a66eb69a1ff826c1f849d67fd25736aae735b80a0a327d3622164e0fa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
